export default {
  extends: ['stylelint-config-standard', 'stylelint-config-tailwindcss'],
  plugins: ['stylelint-order'],
  ignoreFiles: ['docs/**', 'dist/**', 'public/**', 'src/assets/img/**', 'src/shared/configs/**'],
  rules: {
    // properties 정렬 규칙
    'order/properties-order': [
      {
        groupName: 'positioning',
        emptyLineBefore: 'never',
        properties: ['position', 'top', 'right', 'bottom', 'left', 'z-index'],
      },
      {
        groupName: 'box-model',
        emptyLineBefore: 'never',
        properties: [
          'display',
          'flex-direction',
          'flex-wrap',
          'justify-content',
          'align-items',
          'align-self',
          'order',
          'width',
          'height',
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'border',
          'border-width',
          'border-style',
          'border-color',
          'border-radius',
          'box-sizing',
        ],
      },
      {
        groupName: 'typography',
        emptyLineBefore: 'never',
        properties: [
          'font',
          'font-family',
          'font-size',
          'font-weight',
          'font-style',
          'line-height',
          'letter-spacing',
          'text-align',
          'text-decoration',
          'text-transform',
          'color',
        ],
      },
      {
        groupName: 'visual',
        emptyLineBefore: 'never',
        properties: [
          'background',
          'background-color',
          'background-image',
          'background-repeat',
          'background-position',
          'background-size',
          'background-clip',
          'background-origin',
          'box-shadow',
          'opacity',
          'outline',
          'outline-width',
          'outline-style',
          'outline-color',
          'outline-offset',
          'filter',
          'mix-blend-mode',
          'isolation',
          'backdrop-filter',
        ],
      },
      {
        groupName: 'misc',
        emptyLineBefore: 'never',
        properties: [
          'cursor',
          'pointer-events',
          'visibility',
          'clip',
          'clip-path',
          'overflow',
          'overflow-x',
          'overflow-y',
          'transform',
          'transform-origin',
          'transition',
          'transition-property',
          'transition-duration',
          'transition-timing-function',
          'transition-delay',
          'animation',
          'animation-name',
          'animation-duration',
          'animation-timing-function',
          'animation-delay',
          'animation-iteration-count',
          'animation-direction',
          'animation-fill-mode',
          'animation-play-state',
        ],
      },
    ],
    'order/properties-alphabetical-order': null,
    'declaration-block-single-line-max-declarations': 1,
    'property-no-vendor-prefix': null,
    'property-no-deprecated': null,
    'selector-class-pattern': '^[_a-zA-z][a-zA-Z0-9_-]+$',
    'selector-id-pattern': '^[_a-zA-z][a-zA-Z0-9_-]+$',
    'custom-property-pattern': '^[_a-zA-z][a-zA-Z0-9_-]+$',
    'no-descending-specificity': null,
    'font-family-no-missing-generic-family-keyword': null,
  },
};
